export const site = {
  name: "Quantum Spike",
  edition: "2026",
  dates: "08–09 October 2026",
  registrationOpen: "10 September 2026",
  registrationClose: "05 October 2026",
  venue: "Department of Physics, Bankura Sammilani College",
  location: "Bankura, West Bengal, India",
  email: "quantum.spike.conf.2026@gmail.com",
  officialSite: "https://sites.google.com/view/quantum-spike-2026/",
  demoSite: "https://sites.google.com/view/quantumspike-demo/",
  registrationUrl: "#registration",
  abstractUrl: "#contact",
  brochure: "/conference-poster.jpg",
  fees: [
    { label: "Students", amount: "₹300" },
    { label: "PhD / Research Scholar", amount: "₹500" },
    { label: "Faculty Members", amount: "₹1000" },
  ],
  topics: [
    "Ultracold Atomic Gases",
    "Quantum Information",
    "Quantum Optics",
    "Condensed Matter Physics",
    "Nanomaterials",
    "Quantum Devices",
    "Nuclear Physics",
    "Optics & Photonics",
    "Fibre Optics",
    "Emerging Technologies",
  ],
  people: {
    patron: { name: "Dr. Swapan Mukhopadhyay", role: "Teacher-in-charge, Bankura Sammilani College" },
    chairperson: { name: "Dr. Mrinmoy Sannigrahi", role: "IQAC Coordinator" },
    convenor: { name: "Dr. Priyam Das", role: "Assistant Professor, Department of Physics" },
    organizing: [
      { name: "Dr. Swapnadip Roy", role: "Member, IQAC" },
      { name: "Dr. Chakradhar Rajowar", role: "Head & Associate Professor" },
      { name: "Dr. Uttam Mondal", role: "Associate Professor" },
      { name: "Dr. Pradipta Chakraborty", role: "State Aided College Teacher" },
      { name: "Dr. Surajit Bosu", role: "State Aided College Teacher" },
      { name: "Mr. Narendranath Pal", role: "State Aided College Teacher" },
    ],
    resourcePersons: [
      "Prof. Prasanta K. Panigrahi — SoA University",
      "Prof. Ayan Khan — Bennett University",
      "Prof. Ardhendu Shekhar Patra — SKBU",
      "Prof. Bharti Sarkar — Jadavpur University",
      "Dr. Raka Dasgupta — Calcutta University",
      "Dr. Nasir Alam — Bankura University",
      "Dr. Balaram Dey — Bankura University",
      "Dr. Baibaswata Bhattacharjee — Ramananda College",
      "Dr. Ratan Sarkar — Jogesh Chandra Chaudhuri College",
    ],
  },
} as const;
